### ISSUE TITLE
[Collection Upload] Problem whend edit my form

### ISSUE THREAD

**Issue by nicoip** [symfony2admingenerator/FormExtensionsBundle#45] opened 2015-09-03 15:37 UTC
I have a collection of image.
When I import my images in my form, everything works.
When I edit my form, I have an error message

```Catchable Fatal Error: Argument 1 passed to Ip\ItemBundle\Entity\Image::setItem() must be an instance of Ip\ItemBundle\Entity\Item, null given, called in \vendor\symfony\symfony\src\Symfony\Component\PropertyAccess\PropertyAccessor.php on line 410 and defined ```

My Image Entity  :
 ```
...
    /**
     * Set item
     *
     * @param \Ip\ItemBundle\Entity\Item $item
     * @return Image
     */
    public function setItem(\Ip\ItemBundle\Entity\Item $item)
    {
        $this->item = $item;

        return $this;
    }
...
 ```

Thank you !

**Comment by bobvandevijver** [comment] 2015-09-03 17:32
Duplicate of https://github.com/symfony2admingenerator/GeneratorBundle/issues/206.

**Closed by bobvandevijver** 2015-09-03 17:32 UTC
